// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC35z6GU5F9Wmcv1osld15THcAmo58Y0kw',
    appId: '1:522103144883:web:aa6ee013f231f43aae8bc6',
    messagingSenderId: '522103144883',
    projectId: 'dummy-ecom-beb97',
    authDomain: 'dummy-ecom-beb97.firebaseapp.com',
    storageBucket: 'dummy-ecom-beb97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU1hXlz6MEdHfPHwzz3J9MNOImW9okwU4',
    appId: '1:522103144883:android:d28e75eeff90c648ae8bc6',
    messagingSenderId: '522103144883',
    projectId: 'dummy-ecom-beb97',
    storageBucket: 'dummy-ecom-beb97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeUqqDD66wOaVp10gXBL8SYXuI17RcwPs',
    appId: '1:522103144883:ios:5701922cebb0b9f6ae8bc6',
    messagingSenderId: '522103144883',
    projectId: 'dummy-ecom-beb97',
    storageBucket: 'dummy-ecom-beb97.appspot.com',
    iosBundleId: 'com.example.ecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeUqqDD66wOaVp10gXBL8SYXuI17RcwPs',
    appId: '1:522103144883:ios:5701922cebb0b9f6ae8bc6',
    messagingSenderId: '522103144883',
    projectId: 'dummy-ecom-beb97',
    storageBucket: 'dummy-ecom-beb97.appspot.com',
    iosBundleId: 'com.example.ecom',
  );
}
